services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PackCode*503
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  app:
    build: .
    container_name: spring-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: PackCode*503
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      #SERVER_PORT: 4000
      SECURITY_JWT_SECRET_KEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      SECURITY_JWT_EXPIRATION_TIME: 3600000
    ports:
      - "4000:8080"
    networks:
      - spring-net
    restart: always

volumes:
  postgres_data:

networks:
  spring-net:
